apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: restauranty

type: Opaque

stringData:
  SECRET: "MySecret1!"

  MONGODB_URI: "mongodb://admin:Restauranty123@mongo-mongodb-headless.database.svc.cluster.local:27017/resturanty?replicaSet=rs0&authSource=admin"

  CLOUD_NAME: "dhg5jugra"

  CLOUD_API_KEY: "915763731447728"

  CLOUD_API_SECRET: "GvrRvIkfK9PDd3klG5wtdoCUjtA"