apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: restauranty

type: Opaque

stringData:

  SECRET: "MySecret1!"

  MONGODB_URI: "mongodb://admin:Restauranty123@mongo-mongodb-headless.database.svc.cluster.local:27017/resturanty?replicaSet=rs0&authSource=admin"

  CLOUD_NAME: "XXXXX"

  CLOUD_API_KEY: "XXXXXXXXXXX"

  CLOUD_API_SECRET: "XXXXXXXXXXXXXXXXX"