apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: discounts-ingress-internally
  namespace: restauranty

spec:

  podSelector:

    matchLabels:

      app: discounts

  policyTypes:

  - Ingress

  ingress:
  - from:

    - ipBlock:

        cidr: 10.0.0.0/8

    ports:

    - protocol: TCP
      port: 3002