name: Build and Deploy

on:
  push:
    branches:
      - develop
      - main

env:
  REGISTRY: restaurantyacrlananh.azurecr.io
  NAMESPACE: restauranty

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.detect.outputs.services }}

    steps:

    - uses: actions/checkout@v4

      with:
        fetch-depth: 2

    - id: detect

      run: |

        CHANGED="[]"

        if git diff --name-only HEAD~1 HEAD | grep '^apps/backend/auth/'; then
          CHANGED=$(echo "$CHANGED" | jq '. + ["auth"]')
        fi

        if git diff --name-only HEAD~1 HEAD | grep '^apps/backend/items/'; then
          CHANGED=$(echo "$CHANGED" | jq '. + ["items"]')
        fi

        if git diff --name-only HEAD~1 HEAD | grep '^apps/backend/discounts/'; then
          CHANGED=$(echo "$CHANGED" | jq '. + ["discounts"]')
        fi

        if git diff --name-only HEAD~1 HEAD | grep '^apps/client/'; then
          CHANGED=$(echo "$CHANGED" | jq '. + ["client"]')
        fi

        echo "services=$CHANGED" >> $GITHUB_OUTPUT

  build:

    needs: detect

    if: needs.detect.outputs.services != '[]'

    runs-on: ubuntu-latest

    strategy:

      matrix:

        service:
          ${{ fromJson(needs.detect.outputs.services) }}

    steps:

    - uses: actions/checkout@v4

    - name: Docker Login

      uses: docker/login-action@v3

      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Setup Buildx

      uses: docker/setup-buildx-action@v3

    - name: Select Build Context

      run: |

        if [ "${{ matrix.service }}" = "client" ]; then
          echo "DIR=apps/client" >> $GITHUB_ENV
        else
          echo "DIR=apps/backend/${{ matrix.service }}" >> $GITHUB_ENV
        fi

    - name: Build and Push

      uses: docker/build-push-action@v6

      with:
        context: ${{ env.DIR }}

        push: true

        platforms: linux/amd64

        tags: |
          ${{ env.REGISTRY }}/${{ matrix.service }}:${{ github.sha }}

  deploy:

    needs:
      - detect
      - build

    if: needs.detect.outputs.services != '[]'

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Configure kubectl

      run: |

        mkdir -p ~/.kube

        echo '${{ secrets.KUBE_CONFIG }}' \
        > ~/.kube/config

    - name: Deploy changed services

      run: |

        SERVICES='${{ needs.detect.outputs.services }}'

        echo $SERVICES | jq -r '.[]' | while read SERVICE
        do

          kubectl set image \
          deployment/$SERVICE \
          $SERVICE=${{ env.REGISTRY }}/$SERVICE:${{ github.sha }} \
          -n ${{ env.NAMESPACE }}

          kubectl rollout status \
          deployment/$SERVICE \
          -n ${{ env.NAMESPACE }}

        done